AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create VPC, EC2, and S3

Resources:

  # VPC
  SolomanVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: soloman-cloudformation-vpc

  # Internet Gateway
  SolomanInternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref SolomanVPC
      InternetGatewayId: !Ref SolomanInternetGateway

  # Public Subnet
  SolomanPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SolomanVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: ap-south-2a
      Tags:
        - Key: Name
          Value: soloman-cloudformation-subnet

  # Route Table
  SolomanRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SolomanVPC

  # Route to Internet
  SolomanRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref SolomanRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref SolomanInternetGateway

  # Associate Route Table with Subnet
  SolomanSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SolomanPublicSubnet
      RouteTableId: !Ref SolomanRouteTable

  # Security Group
  SolomanSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      VpcId: !Ref SolomanVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  SolomanEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0f58b397bc5c1f2e8
      SubnetId: !Ref SolomanPublicSubnet
      SecurityGroupIds:
        - !Ref SolomanSecurityGroup
      KeyName: solo.pem
      Tags:
        - Key: Name
          Value: soloman-cloudformation-ec2

  # S3 Bucket
  SolomanS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: soloman-cloudformation-s3-bucket-12345

Outputs:

  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref SolomanEC2Instance

  BucketName:
    Description: S3 Bucket Name
    Value: !Ref SolomanS3Bucket
